name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform env:dev'
    runs-on: ubuntu-latest
    environment: dev
    env:
      TF_WORKSPACE: dev
      TF_ARM_USE_MSI: true
      TF_ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      TF_ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      TF_ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Load environment variable
    # - name: Load environment variables from env file
    #   run: cat env-${{ env.TF_WORKSPACE }}/${{ env.TF_WORKSPACE }}.env | grep -v ^# >> $GITHUB_ENV

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # - name: Generates SAS Token
    #   run: utilities/get_sas_azurerm.sh

    - name: Terraform Init
      run: |
        terraform init -backend-config="env-${{ env.TF_WORKSPACE }}/${{ env.TF_WORKSPACE }}.azurerm.tfbackend"

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      if: github.event.inputs.terraform_action == 'plan'
      run: terraform plan

    - name: Terraform Apply
      if: github.event.inputs.terraform_action == 'apply'
      run: terraform apply -auto-approve